name: fstore
publish_to: "none"
description: Mobile commerce app by Flutter

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 3.0.0+3022

environment:
  sdk: ">=2.16.0 <=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  inspireui: ^1.1.1

  # Base
  intl: 0.17.0
  crypto: 3.0.2
  path_provider: 2.0.10
  url_launcher: 6.1.2
  localstorage: 4.0.0+1
  http: 0.13.4
  http_auth: 1.0.1
  share: 2.0.4
  tuple: 2.0.0
  shared_preferences: 2.0.15
  collection: 1.16.0
  quiver: 3.1.0
  async: 2.9.0
  html: 0.15.0
  vector_math: 2.1.2
  path: 1.8.1
  flutter_svg: 1.0.3

  # FIREBASE PACKAGES
  firebase_core: 1.17.0
  firebase_analytics: 9.1.8
  firebase_auth: 3.3.18
  firebase_remote_config: 2.0.7
  firebase_dynamic_links: 4.2.3
  cloud_firestore: 3.1.15

  # STATE MANAGEMENT
  provider: 6.0.2
  get_it: 7.2.0

  # SPLASH SCREEN, ONBOARD
  lottie: 1.3.0
  flutter_native_splash: 2.2.0+1

  # WEB TOOLS
  html_unescape: 2.0.0
  webview_flutter: 3.0.4
  webview_flutter_web: 0.1.0+3
  responsive_builder: 0.4.2
  flutter_inappwebview: 5.4.3+7

  # HTML render
  flutter_widget_from_html_core:
  fwfh_svg:
  fwfh_cached_network_image:
  fwfh_url_launcher:
  fwfh_chewie:

  # MAP
  google_maps_flutter: 2.1.5
  geocode: 1.0.1
  location: 4.4.0

  # AUTHENTICATION
  the_apple_sign_in: 1.1.1
  flutter_facebook_auth: 4.3.4
  google_sign_in: 5.3.1
  sms_autofill: 2.2.0

  # PUSH NOTIFICATION
  firebase_messaging: 11.4.0
  notification_permissions: 0.6.1
  flutter_local_notifications: 9.5.3+1
  onesignal_flutter: 3.3.0

  # FILES, IMAGES
  file_picker: 4.5.1
  cached_network_image: 3.2.1
  image: 3.1.3
  transparent_image: 2.0.0
  image_picker: 0.8.5+3
  flutter_native_image: 0.0.6+1
  flutter_cache_manager: 3.3.0
  wechat_assets_picker: 7.3.0
  photo_manager: 2.1.1

  # ADS
  google_mobile_ads: 1.2.0

  # TOOLS
  google_fonts: 2.3.3
  random_string: 2.3.1
  json_annotation: 4.5.0
  timeago: 3.2.2
  universal_platform: 1.0.0+1
  uuid: 3.0.6
  easy_debounce: 2.0.2+1
  devicelocale: 0.5.2
  visibility_detector: 0.3.3
  rate_my_app: 1.1.3
  flutter_linkify: 5.0.2
  gms_check: 1.0.0
  email_validator: 2.0.1
  new_version: ^0.3.0
  video_player: 2.4.2

  # UI
  flutter_spinkit: 5.1.0
  smooth_page_indicator: 1.0.0+2
  animated_text_kit: 4.2.1
  flash: 2.0.3+2
  flutter_staggered_grid_view: 0.6.1
  pin_code_fields: 7.4.0
  country_code_picker: 2.0.2
  country_pickers: 2.0.0
  intro_slider: 3.0.5
  dropdown_search: 4.0.1
  flutter_zoom_drawer: 3.0.2
  extended_image: 6.2.1
  dotted_decoration: 2.0.0
  awesome_card: 1.1.7

  ### Native Payment
  razorpay_flutter: 1.3.0
  paytm_allinonesdk: 1.1.7

  #### For Listing App
  carousel_slider: 4.1.1

  #### For Shopify GraphQL
  graphql: 5.1.1

  ### For Delivery App
  maps_launcher: 2.0.1


  ### Flutter 3 fix warning
  charts_flutter:
    git:
      url: https://github.com/inspireui/charts.git
      path: charts_flutter
  fwfh_webview:
    git:
      url: https://github.com/inspireui/flutter_widget_from_html.git
      ref: 1f471412850b2c5e558273e8e9a7900b389cf4a6
      path: packages/fwfh_webview
  flutter_swiper_null_safety:
    git: https://github.com/inspireui/flutter_swiper_null_safety
  flare_flutter:
    git:
      url: https://github.com/inspireui/Flare-Flutter.git
      ref: fd4bcba22aae4c028286e453deeb78f3311e689a
      path: flare_flutter
  rive:
    git: https://github.com/inspireui/rive-flutter
  pull_to_refresh:
    git: https://github.com/inspireui/flutter_pulltorefresh
  qr_code_scanner:
    git:
      url: https://github.com/inspireui/qr_code_scanner.git
      ref: 9da3facc45defd3c0775ddb84fd088d822e7edd8
  flutter_calendar_carousel:
    git:
      url: https://github.com/inspireui/flutter_calendar_carousel.git
      ref: 7e1249dfdbd8cb61b7b7e1d0a48cae0eba7ad3ca


  ##---- Extended features ------ ###
  ## Native payment
  flutter_stripe: 3.0.0
  stripe_sdk:
    git:
      url: https://github.com/inspireui/stripe-sdk
      ref: 73acb5aea148b1c442f739037557e1cdf9339ba0
  myfatoorah_flutter:
    git:
      url: https://github.com/inspireui/myfatoorah_flutter.git
      ref: 9e6b4c1af37751a80d70ca896ef02b7b0ce19b04

  ## POS APP && PRINTER FEATURE
  bluetooth_enable_fork: 0.1.4
  flutter_blue_plus: 1.1.3
  flutter_esc_pos_utils: 0.1.4
  esc_pos_bluetooth:
    git: https://github.com/inspireui/esc_pos_bluetooth


  ###---- Some extra featureen is disable by default -----###
  ### ðŸ’³ Facebook Ads
  ### Search "Enable Facebook Ads" & uncomment to use  - https://tppr.me/9Pkf9
  # facebook_audience_network: 1.0.0-nullsafety.0

  ### â–¶ï¸ Audio Feature - support FluxNews only
  ### Search "Enable Audio feature" & uncomment toÃ… use - https://tppr.me/Z1TX5
  audio_video_progress_bar: ^0.10.0
  audio_service: 0.18.3 # Don't update it to 0.18.4
  just_audio: 0.9.21
  flutter_launcher_icons: ^0.9.2

dependency_overrides:
  rxdart: 0.27.0
#  petitparser: 5.0.0

dev_dependencies:
  flutter_lints:
#  intl_utils: ^2.6.1

### Enable to use Flutter Test Driver
#  flutter_driver:
#    sdk: flutter
#  test: 1.16.5
#  dependency_validator: ^3.1.2  # pub run dependency_validator

### Enable Generate Icon library
#  flutter_launcher_icons: ^0.9.2
#  Run this script to generate the app icon: flutter pub run flutter_launcher_icons:main

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - lib/config/
    - lib/config/mocks/
    - lib/config/states/
    - lib/config/stories/
    - assets/icons/brands/
    - assets/icons/credit_cards/
    - assets/icons/tabs/
    - assets/icons/payment/
    - assets/icons/logins/
    - assets/images/
    - assets/images/country/
    - assets/images/favicon/
    - assets/html/
    - google_fonts/

flutter_intl:
  enabled: true
  use_deferred_loading: true
